### ISSUE TITLE
Redimension del Logo

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/primeros-pasos#2]
El logo de la comunidad está a un tamaño desproporcionado a la publicación. 
Para setear los valores de ANCHOxALTO sería de la siguiente manera: 

```
![](./pic/mypic.png =450x400)
```

En el ejemplo anterior se estaría  definiendo una imagen de 450px de ancho por 400 de alto.

**Comment by abr4xas** [comment]
He revisado y eso no se puede hacer :( 
![captura de pantalla 2015-08-23 a la s 16 59 33](https://cloud.githubusercontent.com/assets/405484/9430276/60ef83a2-49b8-11e5-85df-7692155830b2.png)
Y sale esto
![captura de pantalla 2015-08-23 a la s 17 00 06](https://cloud.githubusercontent.com/assets/405484/9430277/7037a1fa-49b8-11e5-98df-de44e33742c0.png)

**Comment by JMEspiz** [comment]
A mi tampoco me funciono para redimencionar, me muestra lo mismo que a @abr4xas
